### ISSUE TITLE
The xlsm it appears it doesn't have the support mark

### ISSUE THREAD

**Issue by gerardoponce76** [jmarxuach/json2xlsm#3]
Hi! your tool looks very interesting for me.. 
When I compile this I get this error message:

java -jar json2xlsm.jar arr1x.json sample.xlsm salida.xlsm
java.io.IOException: getFileMagic() only operates on streams which support mark(int)
        at org.apache.poi.poifs.filesystem.FileMagic.valueOf(FileMagic.java:131)
        at org.apache.poi.poifs.filesystem.NPOIFSFileSystem.hasPOIFSHeader(NPOIFSFileSystem.java:370)
        at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:69)
        at json2xlsm.lib.json2xlsm.json2excel(json2xlsm.java:109)
        at json2xlsm.lib.json2xlsm.ExecuteExport(json2xlsm.java:65)
        at json2xlsm.cli.Main.main(Main.java:31)

When I do it with a pre-compiled version I found, it works great...
I want to make a few changes, since I need this tool to add a new worksheet (insert a new one), and I may try to change it a little bit..  For my solution I need to add several workseets..

But I can't get it to compile right since in my compiled version I get that error..

**Comment by jmarxuach** [comment]
Hi, must be something with IDE project. Java version, Path or included libraries.

What changes do you want to do ?

**Comment by koten551** [comment]
master branch using different version of POI(3.17) due to this problem. Using another branch or POI version 3.8 to fix this.

**Comment by jmarxuach** [comment]
@koten551 is right
